name: postman
version: 5.5.3
grade: devel
summary: API Development Environment
description: |
  Postman is the complete toolchain for API developers, used by more than 3 million developers and 30000 companies worldwide. Postman makes working with APIs faster and easier by supporting developers at every stage of their workflow, and is available for Mac OS X, Windows, Linux and Chrome users.
 
confinement: strict
 
parts:
  postman:
    after: [desktop-gtk2]
    plugin: dump
    source-type: tar
    source: https://dl.pstmn.io/download/latest/linux64
    install: |
     mkdir $SNAPCRAFT_PART_INSTALL/usr/share/Postman
     mv * $SNAPCRAFT_PART_INSTALL/usr/share/Postman
    stage:
     - usr/*
    stage-packages:
      - libasound2
      - libatomic1
      - libc++1
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

  desktop:
    after: [postman]
    plugin: dump
    source: .
    install: |
     mkdir $SNAPCRAFT_PART_INSTALL/usr $SNAPCRAFT_PART_INSTALL/usr/share $SNAPCRAFT_PART_INSTALL/usr/share/applications
     mv postman.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications
    stage:
     - usr/share/applications/postman.desktop
 
apps:
  postman:
    command: bin/desktop-launch $SNAP/usr/share/Postman/Postman
    desktop: usr/share/applications/postman.desktop
    plugs: [home, network, network-observe, x11, wayland, opengl, desktop, desktop-legacy, unity7, gsettings, browser-support]
