name: postman
version: 5.5.3
grade: devel
summary: postman
description: |
  API development
 
confinement: devmode
 
parts:
  postman:
    plugin: dump
    source-type: tar
    source: https://dl.pstmn.io/download/latest/linux64
    stage-packages:
     - libx11-xcb1
     - libx11-6
     - libxau6
     - libxcomposite1
     - libxcursor1
     - libxdamage1
     - libxdmcp6
     - libxext6
     - libxfixes3
     - libxi6
     - libxinerama1
     - libxrandr2
     - libxrender1
     - libxss1
     - libxtst6
     - libasound2
     - libatk1.0-0
     - libavahi-client3
     - libavahi-common3
     - libcairo2
     - libcups2
     - libdatrie1
     - libdbus-glib-1-2
     - libfontconfig1
     - libgconf-2-4
     - libgtk2.0-0
     - libgdk-pixbuf2.0-0
     - libgraphite2-3
     - libharfbuzz0b
     - libnspr4
     - libnss3
     - libpango-1.0-0
     - libpangocairo-1.0-0
     - libpangoft2-1.0-0
     - libpixman-1-0
     - libthai0
     - libxcb-render0
     - libxcb-shm0
     - libxcb1
     - libatomic1
     - libc++1
     - libnotify4
     - libpulse0
    after: [desktop-gtk2]
  desktop:
    after:
     - postman
    plugin: dump
    source: .
    stage:
     - postman.desktop
    prime:
     - postman.desktop
 
apps:
  postman:
    command: desktop-launch Postman
    desktop: postman.desktop
    plugs: [home, network, x11, wayland, hardware-observe, opengl, time-control, desktop, desktop-legacy, unity7, gsettings, browser-support, screen-inhibit-control]
